#MineStore by @vincenzopio

store-api:
  address: "https://store.myserver.com/api/"
  api-key: "store_api_key"

#I suggest using "LISTENER" instead of "SOCKET" since ports must be open.
store-connection:
  mode: LISTENER
  socket:
    port: 33266
    password: "socket_password"
  listener:
    secret_key: "super_secret_key"
